### ISSUE TITLE
[Bug]: PUID & PGID set by environmental  variables not applying to downloaded/imported files

### ISSUE THREAD

**Issue by sea3pea0** [RandomNinjaAtk/docker-lidarr-extended#217]
Music Videos imported to library as user/group root even though PUID & PGID are set in docker compose file (I haven't tried audio download from the scripts yet so I don't know if this is also the case for audio)

Since my library is owned by user/group 1000 and the plex docker container is set to PUID=1000 & PGID=1000, plex doesn't have permission to access the files imported by docker-lidarr-extended. I have to manually change ownership to allow plex to access the files downloaded by docker-lidarr-extended. As a work around I could set up a post-process script to change ownership but this wouldn't be ideal

**To Reproduce**
Docker Compose Entry:
```
  lidarr:
    image: randomninjaatk/lidarr-extended:latest
    container_name: lidarr
    volumes:
      - /mytorrentdownload:/downloads:shared
      - /myconfig:/config
      - /mybackups:/backups:shared
      - /mylidarrextended:/downloads-lidarr-extended
      - /mymusic:/music
      - /mymusicvideos:/music-videos
    environment:
      - TZ=Pacific/Honolulu
      - PUID=1000
      - PGID=1000
      - enableAudioScript=true
      - enableVideoScript=true
      - scriptInterval=15m
      - configureLidarrWithOptimalSettings=false
      - searchSort=date
      - audioFormat=native
      - audioBitrate=lossless
      - requireQuality=true
      - enableReplaygainTags=true
      - audioLyricType=deezer
      - dlClientSource=deezer
      - arlToken=[SECRET]
      - tidalCountryCode=US
      - addDeezerTopArtists=false
      - addDeezerTopAlbumArtists=false
      - addDeezerTopTrackArtists=false
      - topLimit=10
      - addRelatedArtists=false
      - numberOfRelatedArtistsToAddPerArtist=5
      - lidarrSearchForMissing=true
      - addFeaturedVideoArtists=false
      - plexUrl=http://x.x.x.x:32400
      - plexToken=[SECRET]
      - youtubeSubtitleLanguage=en
      - enableQueueCleaner=false
      - matchDistance=5
      - enableBeetsTagging=true
      - beetsMatchPercentage=90
      - retryNotFound=90
      - webHook=https://discord.com/api/webhooks/[SECRET]
```
**Expected behavior**
Files and folders created/downloaded by docker-lidarr-extended to the /mylidarrextended:/downloads-lidarr-extended and then imported to /mymusicvideos:/music-videos expected to have the ownership set by:
```
      - PUID=1000
      - PGID=1000
```

**Log Data**
No log data regarding setting file/folder ownership found

**Docker Info:**
 - Docker Version: 23.0.1, build a5ee5b1
 - Extended Script Version: 1.0.309
