### ISSUE TITLE
[Bug]: No files present after download

### ISSUE THREAD

**Issue by fscorrupt** [RandomNinjaAtk/docker-lidarr-extended#247]
i set up lidarr extended yesterday and configured everything.

this is my yaml:
```
version: "2.1"
services:
    lidarr-extended:
        hostname: "lidarr-extended"
        container_name: "lidarr-extended"
        environment:
            - "PGID=${ID}"
            - "PUID=${ID}"
            - "TZ=${TZ}"
            - "UMASK=${UMASK}"
            - "DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr"
            - "TP_THEME=${LIDARRTHEME}"
            - "autoStart=true"
            - "enableAudioScript=true"
            - "enableVideoScript=false"
            - "scriptInterval=15m"
            - "configureLidarrWithOptimalSettings=true"
            - "searchSort=date"
            - "audioFormat=native"
            - "audioBitrate=lossless"
            - "requireQuality=true"
            - "enableReplaygainTags=true"
            - "audioLyricType=both"
            - "dlClientSource=deezer"
            - "arlToken=REDACTED"
            - "tidalCountryCode=US"
            - "addDeezerTopArtists=false"
            - "addDeezerTopAlbumArtists=false"
            - "addDeezerTopTrackArtists=false"
            - "topLimit=0"
            - "addRelatedArtists=false"
            - "numberOfRelatedArtistsToAddPerArtist=5"
            - "addFeaturedVideoArtists=false"
            - "plexUrl=http://plex:32400"
            - "plexToken=REDACTED"
            - "youtubeSubtitleLanguage=en"
            - "enableQueueCleaner=false"
        image: "randomninjaatk/lidarr-extended:latest"
        restart: "${RESTARTAPP}"
        networks:
            - ${DOCKERNETWORK}
        security_opt:
            - "${SECURITYOPS}:${SECURITYOPSSET}"
        volumes:
            - "${APPFOLDER}/lidarr-extended:/config:rw"
            - "unionfs:/mnt"
            - "/mnt/downloads/amd:/downloads-lidarr-extended"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "dockupdater.enable=true"
            - "traefik.http.routers.lidarr-extended-rtr.entrypoints=https"
            - "traefik.http.routers.lidarr-extended-rtr.rule=Host(`lidarr-extended.${DOMAIN}`)"
            - "traefik.http.routers.lidarr-extended-rtr.tls=true"
            - "traefik.http.routers.lidarr-extended-rtr.tls.certresolver=dns-cloudflare"
            - "traefik.http.routers.lidarr-extended-rtr.middlewares=chain-authelia@file"
            - "traefik.http.routers.lidarr-extended-rtr.service=lidarr-extended-svc"
            - "traefik.http.services.lidarr-extended-svc.loadbalancer.server.port=8686"
networks:
    proxy:
        driver: proxy
        external: true
volumes:
    unionfs:
        driver: local-persist
        driver_opts:
            mountpoint: /mnt
```

i added indexers to lidar and also sab as download client and my root folder `/mnt/unionfs/music`
if i manually download in lidarr threw sab all works.

but if it starts downloading via deezer i have following behavior
It searches, it downloads the files to the incomplete folder then i see in log "all done" after that the files are gone, they are not present in the complete folder or in my music root folder, also under incomplete they are gone.

Any idea on how i can track this? cause i have no errors in log:
![image](https://github.com/RandomNinjaAtk/docker-lidarr-extended/assets/45659314/3ce7048f-21a0-490f-a9fc-6d3af318e8bf)
