### ISSUE TITLE
Trouble starting up docker image

### ISSUE THREAD

**Issue by bcullman** [RandomNinjaAtk/docker-lidarr-extended#5]
same issue as seen here:
https://github.com/RandomNinjaAtk/docker-amvd/issues/30

Checking portainer, I see the following in the logs:

```
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
```

at somepoint the docker container restarts, and this cycle repeats.

my docker-compose file

```
version: "2.1"
services:
  lidarr-extended:
    image: randomninjaatk/lidarr-extended
    container_name: lidarr-extended
    volumes:
      - .config:/config
      - /mnt/downloads:/downloads
      - /mnt/music:/music
      - /mnt/music-videos:/music-videos
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - autoStart=true
      - configureLidarrWithOptimalSettings=true
      - audioFormat=native
      - audioBitrate=lossless
      - audioLyricType=both
      - dlClientSource=both
      - arlToken=Token_Goes_Here
      - tidalCountryCode=US
      - addDeezerTopArtists=true
      - addDeezerTopAlbumArtists=true
      - addDeezerTopTrackArtists=true
      - topLimit=10
      - addRelatedArtists=false
      - numberOfRelatedArtistsToAddPerArtist=5
      - beetsMatchPercentage=90
      - plexUrl=http://192.168.0.100:32400
      - plexToken=[myPlexToken]
    ports:
      - 8680:8686
    restart: unless-stopped
```
